
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution
# refrance for me: https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=apk#step_2_authenticate_with_firebase
platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    # sh "flutter clean"
    # sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons --split-per-abi"
    firebase_app_distribution(
        app: "1:612456605636:android:b61a3111eed95884fe6691",#from firebase 
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-arm64-v8a-production-release.apk",
        testers: "mahyounes73@gmail.com",
        release_notes: "first distribution from fastlane",
        upload_timeout: 2400   # for increased timeout ,, internet weak ,, 20 minutes
  )
  end
end
# pubspec.yaml version: 1.0.0+1 modifiy
# all commands are executed from the android // cd android
# sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
# to run   fastlane <lane>   // fastlane android firebase_distribution